var tin1= {
    matin:1,
    img: "../img/tintuc/tin1.webp",
    ten:'Digital Show 2022 "Mơ nhuộm nắng"',
    ngaytochuc:'04/04/2022',
    noidung:"Vào tối 20h00 ngày 09 tháng 04 năm 2022 tới đây, Thương hiệu thời trang hàng đầu Việt Nam IVY moda sẽ phát sóng show diễn thời trang phiên bản “công nghệ” mang tên “Mơ nhuộm nắng” SS 2022 trên fanpage chính thức và các nền tảng online khác. Đây cũng là lần đầu tiên, một Thương hiệu thời trang Việt Nam tiên phong mang đến những trải nghiệm mới mẻ của Digital Show mà không làm mất đi tinh thần và sự sôi động của sàn Runway."+

+"Vào năm thứ 17 ở độ tuổi trưởng thành của một Thương hiệu thời trang, IVY moda không trở nên già cỗi mà càng chứng minh được tiềm lực mạnh mẽ, nhạy cảm với xu hướng và khả năng thích nghi cao, cởi mở với sự phát triển của công nghệ.  Sau những mùa sống với đam mê và nhiệt huyết với thời trang trên sàn Runway từ năm 2015 đến nay, IVY moda đánh dấu sự chuyển mình bằng bước đi mới đầy thú vị của Tổng Giám đốc Nguyễn Lê Vũ Linh, khi mang show diễn thời trang truyền thống lên một tầm cao mới."
+"Với vốn liếng con nhà nghề, cùng sự đam mê, trải nghiệm học tập và làm thời trang ở thị trường quốc tế, Vũ Linh thể hiện vai trò cầm trịch Bản tuyên ngôn “số hoá” đầy thú vị với Digital Fashion Show Spring Summer 2022 mang tên “Mơ nhuộm nắng”."
+"Đón đầu xu hướng thời trang thế giới, cân bằng sao cho phù hợp với nhu cầu mong muốn mặc đẹp và phong cách của phụ nViệt là định hướng của Tổng Giám đốc IVY moda Nguyễn Lê Vũ Linh khi đảm nhiệm trong vai trò mới."    
+ "Sau đại dịch Covid-19 diễn ra, thị trường thời trang trên thế giới lẫn trong nước đều xuất hiện các xu hướng tất yếu để chuyển đổi hình thức tiếp cận với khách hàng, trong số đó, hình thức show diễn trực tiếp, sự kiện được chuyển sang Digital Fashion – một phiên bản công nghệ của show diễn thời trang. Thay vì trình diễn trước hàng trăm khán giả theo dõi trực tiếp, người mẫu catwalk giữa sân khấu chứa hàng loạt thiết bị ghi hình, phục vụ cho việc phát sóng online."
+"Mơ nhuộm nắng Spring Summer 2022 của IVY moda như một buổi gặp gỡ gửi gắm nhiều cảm xúc, nhiều động lực, nhiều sự yêu thương đến với phái đẹp qua những thiết kế mang tuyên ngôn cá nhân và xây dựng phong cách riêng cho từng quý cô. Để họ có thể trở nên xinh đẹp hơn, tỏa sáng hơn, tự tin hơn tiếp tục ấp ủ và thực hiện ước mơ của mình. Khi những ước mơ hội tụ lại cũng giống như năng lượng từ vũ trụ đem đến may mắn và bắt đầu một sức sống mới như nắng ban mai."
+"Concept của sàn diễn catwalk tái hiện chu kỳ của một ngày, từ lúc hoàng hôn buông xuống đến khi chờ đón bình minh ngày mới xuất hiện. Không gian của show diễn khiến khán giả chìm đắm trong sự tự do mới, cảm giác lạc quan bởi bầu không khí thơ mộng như một giấc mơ đẹp được hiện thực hoá. Với ba màn trình diễn, digital show “Mơ nhuộm nắng” lần lượt mô tả từng trạng thái sắc độ, cung bậc cảm xúc, từ sự hòa quyện từng khối màu đỏ sang cam rồi tím đầy mê hoặc của hoàng hôn, đến hoa đậu thơm bừng nở quyến rũ, căng tràn trên nền ombre biến chuyển nhiều sắc thái, để chờ đón bình minh ngày mới với nhiều gam màu nóng, tươi vui, rực rỡ của ánh nắng. Khắc hoạ giấc mơ của kẻ “Tuyên ngôn thời trang” được hiện thực hoá ở một phiên bản công nghệ tầm cỡ."    
+"Bên cạnh Fashion Show, IVY moda cũng có buổi giao lưu, chia sẻ gần gũi với những thông tin cực hot, chưa từng bật mí từ dàn khách mời đang được săn đón: Nhóm nhạc Da LAB, Ca sỹ Hoà Minzy, Ca sỹ Cara…"
+" Do tình hình dịch bệnh khó lường, nên quyết định triển khai Digital Fashion show chỉ được đưa ra trước 2 tháng so với ý định ban đầu là thực hiện show offline. Để đảm bảo sự an toàn cho khách hàng của IVY moda và mang đến một trải nghiệm công nghệ mới mẻ về show diễn cho các tín đồ thời trang. Dù là tiếp cận với hình thức khác biệt so với tất cả các show diễn thời trang của IVY moda trước đây, nhưng thương hiệu vẫn đảm bảo đem lại cảm xúc thăng hoa cho quý khách hàng và khán giả theo dõi qua các kênh online."
+"Cùng đón xem Digital Show “Mơ nhuộm nắng” Spring Summer 2022 trên Fanpage chính thức của Thương hiệu thời trang IVY moda vào lúc 20h00 Thứ bảy, ngày 09 tháng 04 năm 2022.",
 mota:"Thương hiệu thời trang hàng đầu Việt Nam IVY moda sẽ phát sóng show diễn thời trang phiên bản “công nghệ” mang tên “Mơ nhuộm nắng” SS 2022 trên fanpage chính thức và các nền tảng online khác. Đây cũng là lần đầu tiên, một Thương hiệu thời trang Việt Nam"
}

var tin2= {
    matin:2,
    img: "../img/tintuc/tin2.webp",
    ten:'Spring Love - BST Xuân - Hè mới nhất',
    ngaytochuc:'09/03/2022',
    noidung:"Vào tối 20h00 ngày 09 tháng 04 năm 2022 tới đây, Thương hiệu thời trang hàng đầu Việt Nam IVY moda sẽ phát sóng show diễn thời trang phiên bản “công nghệ” mang tên “Mơ nhuộm nắng” SS 2022 trên fanpage chính thức và các nền tảng online khác. Đây cũng là lần đầu tiên, một Thương hiệu thời trang Việt Nam tiên phong mang đến những trải nghiệm mới mẻ của Digital Show mà không làm mất đi tinh thần và sự sôi động của sàn Runway."+

+"Vào năm thứ 17 ở độ tuổi trưởng thành của một Thương hiệu thời trang, IVY moda không trở nên già cỗi mà càng chứng minh được tiềm lực mạnh mẽ, nhạy cảm với xu hướng và khả năng thích nghi cao, cởi mở với sự phát triển của công nghệ.  Sau những mùa sống với đam mê và nhiệt huyết với thời trang trên sàn Runway từ năm 2015 đến nay, IVY moda đánh dấu sự chuyển mình bằng bước đi mới đầy thú vị của Tổng Giám đốc Nguyễn Lê Vũ Linh, khi mang show diễn thời trang truyền thống lên một tầm cao mới."
+"Với vốn liếng con nhà nghề, cùng sự đam mê, trải nghiệm học tập và làm thời trang ở thị trường quốc tế, Vũ Linh thể hiện vai trò cầm trịch Bản tuyên ngôn “số hoá” đầy thú vị với Digital Fashion Show Spring Summer 2022 mang tên “Mơ nhuộm nắng”."
+"Đón đầu xu hướng thời trang thế giới, cân bằng sao cho phù hợp với nhu cầu mong muốn mặc đẹp và phong cách của phụ nViệt là định hướng của Tổng Giám đốc IVY moda Nguyễn Lê Vũ Linh khi đảm nhiệm trong vai trò mới."    
+ "Sau đại dịch Covid-19 diễn ra, thị trường thời trang trên thế giới lẫn trong nước đều xuất hiện các xu hướng tất yếu để chuyển đổi hình thức tiếp cận với khách hàng, trong số đó, hình thức show diễn trực tiếp, sự kiện được chuyển sang Digital Fashion – một phiên bản công nghệ của show diễn thời trang. Thay vì trình diễn trước hàng trăm khán giả theo dõi trực tiếp, người mẫu catwalk giữa sân khấu chứa hàng loạt thiết bị ghi hình, phục vụ cho việc phát sóng online."
+"Mơ nhuộm nắng Spring Summer 2022 của IVY moda như một buổi gặp gỡ gửi gắm nhiều cảm xúc, nhiều động lực, nhiều sự yêu thương đến với phái đẹp qua những thiết kế mang tuyên ngôn cá nhân và xây dựng phong cách riêng cho từng quý cô. Để họ có thể trở nên xinh đẹp hơn, tỏa sáng hơn, tự tin hơn tiếp tục ấp ủ và thực hiện ước mơ của mình. Khi những ước mơ hội tụ lại cũng giống như năng lượng từ vũ trụ đem đến may mắn và bắt đầu một sức sống mới như nắng ban mai."
+"Concept của sàn diễn catwalk tái hiện chu kỳ của một ngày, từ lúc hoàng hôn buông xuống đến khi chờ đón bình minh ngày mới xuất hiện. Không gian của show diễn khiến khán giả chìm đắm trong sự tự do mới, cảm giác lạc quan bởi bầu không khí thơ mộng như một giấc mơ đẹp được hiện thực hoá. Với ba màn trình diễn, digital show “Mơ nhuộm nắng” lần lượt mô tả từng trạng thái sắc độ, cung bậc cảm xúc, từ sự hòa quyện từng khối màu đỏ sang cam rồi tím đầy mê hoặc của hoàng hôn, đến hoa đậu thơm bừng nở quyến rũ, căng tràn trên nền ombre biến chuyển nhiều sắc thái, để chờ đón bình minh ngày mới với nhiều gam màu nóng, tươi vui, rực rỡ của ánh nắng. Khắc hoạ giấc mơ của kẻ “Tuyên ngôn thời trang” được hiện thực hoá ở một phiên bản công nghệ tầm cỡ."    
+"Bên cạnh Fashion Show, IVY moda cũng có buổi giao lưu, chia sẻ gần gũi với những thông tin cực hot, chưa từng bật mí từ dàn khách mời đang được săn đón: Nhóm nhạc Da LAB, Ca sỹ Hoà Minzy, Ca sỹ Cara…"
+" Do tình hình dịch bệnh khó lường, nên quyết định triển khai Digital Fashion show chỉ được đưa ra trước 2 tháng so với ý định ban đầu là thực hiện show offline. Để đảm bảo sự an toàn cho khách hàng của IVY moda và mang đến một trải nghiệm công nghệ mới mẻ về show diễn cho các tín đồ thời trang. Dù là tiếp cận với hình thức khác biệt so với tất cả các show diễn thời trang của IVY moda trước đây, nhưng thương hiệu vẫn đảm bảo đem lại cảm xúc thăng hoa cho quý khách hàng và khán giả theo dõi qua các kênh online."
+"Cùng đón xem Digital Show “Mơ nhuộm nắng” Spring Summer 2022 trên Fanpage chính thức của Thương hiệu thời trang IVY moda vào lúc 20h00 Thứ bảy, ngày 09 tháng 04 năm 2022.",
 mota:"Thương hiệu thời trang hàng đầu Việt Nam IVY moda sẽ phát sóng show diễn thời trang phiên bản “công nghệ” mang tên “Mơ nhuộm nắng” SS 2022 trên fanpage chính thức và các nền tảng online khác. Đây cũng là lần đầu tiên, một Thương hiệu thời trang Việt Nam"
}

var dstin = [tin1,tin2]
localStorage.setItem("dstin", JSON.stringify(dstin))